---
- hosts: mywebservers
  become: yes
  tasks:
  - name: install apache2 on ubuntu server
    apt: 
        name: "{{mywebpackonubuntu}}"
        update_cache: yes 
        state: latest

  - name: install java on ubuntu server
    apt: 
        name: "{{myjavainstallonubuntu}}"
        update_cache: yes 
        state: latest