---
- hosts: all
  become: yes
  tasks:
  - name: install apache2 server
    apt:
        name: apache2
        state: present
    when: ansible_os_family== "Debian"

  - name: Start service apache2, if not started
    service:
      name: apache2
      state: started
    when: ansible_os_family== "Debian"

