---
- hosts: all
  become: yes
  tasks:
  - name: install apache2 server
    apt:
        name: apache2
        state: present

  - name: Start service apache2, if not started
    service:
      name: apache2
      state: started





  - name: install git server
    apt:
        name: git 
        state: present

  - name: Start service git, if not started
    service:
      name: git
      state: started




  - name: install wget
    apt:
        name: wget 
        state: present

  - name: Start service wget, if not started
    service:
      name: wget
      state: started


