---
- hosts: mywebservers
  become: yes
  tasks:  
  - name: install java on ubuntu server
    apt: 
        name: "{{myjavainstallonubuntu}}"
        update_cache: yes 
        state: latest
        