---
- hosts: 172.31.4.196
  become: yes
  tasks:
  - name: i want to execute any linux command
    command: hostname -f
    register: myfirsttaskresult

  - name: i want to display result which is in myfirsttaskresult
    debug: 
       msg: "{{myfirsttaskresult}}"
    